Geometry:
  Parametric Surface:
    Layer Extents:
      SO:  [[0.0,0.0,0.0], [4000.0,4000.0,100.0]] 
      SP:  [[0.0,0.0,100.0],[4000.0,4000.0,150.0]]
      SR:  [[0.0,0.0,150.0], [4000.0,4000.0,350.0]]
      SLM: [[0.0, 0.0,350.0], [4000.0, 4000.0, 450.0]]
  Cell Distribution:
    STIM:
      SO:  0
      SP:  1000
      SR:  0
      SLM: 0
    PYR:
      SO:  0
      SP:  80000
      SR:  0
      SLM: 0
    PVBC:
      SO:  352
      SP:  1034
      SR:  88
      SLM: 0
    OLM:
      SO:  438
      SP:  0
      SR:  0
      SLM: 0
Connection Generator:
  Axon Extent:
    # Axonal extent in um [S-T, M-L]
    STIM:
      default:
        width: [1000.0, 1000.0]
        offset: [0,0]
    PYR:
      default:
        width: [1000.0, 1000.0]
        offset: [0,0]
    PVBC: # soma in layer pyramidale, PV+
      default:
        width: [1000.0, 1000.0]
        offset: [0,0]
    OLM: # soma in layer oriens, SOM+
      default:
        width: [840.0, 500.0]
        offset: [0,0]
  Synapses: !include synapses.yml
Cell Types: !include cell_types.yml