## Model configuration of microcircuit network
Model Name: Microcircuit
Dataset Name: Microcircuit
Definitions: !include Definitions.yaml
Global Parameters: !include Global.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Connection Generator: !include Microcircuit_Connections.yaml
Cell Data: MiV_Cells_Microcircuit_20221026.h5
Connection Data: MiV_Connections_Microcircuit_20221026.h5
Recording: !include Recording.yaml
Stimulus: !include Input_Configuration.yaml
Analysis: !include Analysis_Configuration.yaml
Cell Types:
  PYR:
    template: SC_nrn
    mechanism file: PYR_SoldadoMagraner.yaml
    synapses:
      density: !include PYR_synapse_density.yaml
  OLM:
    template: OLMCell
    synapses:
      density: !include OLM_synapse_density.yaml
  PVBC:
    template: PVBasketCell
    synapses:
      density: !include PVBC_synapse_density.yaml
  STIM:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
