## Model configuration of microcircuit network
Network Clamp:  !include Network_Clamp.yaml
Model Name: Microcircuit_Small_Tomko_PR
Dataset Name: Microcircuit_Small
Definitions: !include Definitions.yaml
Global Parameters: !include Global.yaml
Geometry: !include Geometry_Small.yaml
Random Seeds: !include Random.yaml
Connection Generator: !include Microcircuit_Connections.yaml
Cell Data: MiV_Cells_Microcircuit_Small_20220410.h5
Connection Data: MiV_Connections_Microcircuit_Small_20220410.h5
Recording: !include Recording.yaml
Stimulus: !include Input_Configuration.yaml
Analysis: !include Analysis_Configuration.yaml
Cell Types:
  PYR:
    template: TomkoPyramidalCell
    synapses:
      density: !include PYR_synapse_density.yaml
  OLM:
    template: PRN_nrn
    template file: PRN_nrn.hoc
    mechanism file: CA1_OLM_PR_config.yaml
    synapses:
      density: !include OLM_synapse_density.yaml
  PVBC:
    template: PRN_nrn
    template file: PRN_nrn.hoc
    mechanism file: CA1_PVBC_PR_config.yaml
    synapses:
      density: !include PVBC_synapse_density.yaml
  STIM:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train
