param_config_name: "Weight all"
temporal_resolution: 50. # ms
Network Optimization:
  Features:
    - class: miv_simulator.network_objectives.MeanFiringRateFeature
    - class: miv_simulator.network_objectives.FractionActiveFeature
    - class: miv_simulator.network_objectives.FiringRateStabilityFeature
      kwargs:
        temporal_resolution: 2.0
  Objectives:
    - class: miv_simulator.network_objectives.TargetRateObjective
      name: PYR firing rate
      pop_name: PYR
      kwargs:
        target_rate: 2.0
    - class: miv_simulator.network_objectives.TargetMeanFractionActiveObjective
      name: PYR mean fraction active per time bin
      pop_name: PYR
      kwargs:
        target_value: 0.4
    - class: miv_simulator.network_objectives.TargetRateObjective
      name: PVBC firing rate
      pop_name: PVBC
      kwargs:
        target_rate: 25.0
    - class: miv_simulator.network_objectives.TargetMeanFractionActiveObjective
      name: PVBC mean fraction active per time bin
      pop_name: PVBC
      kwargs:
        target_value: 0.9
    - class: miv_simulator.network_objectives.TargetMeanFractionActiveObjective
      name: OLM mean fraction active per time bin
      pop_name: OLM
      kwargs:
        target_value: 0.9
  Constraints:
    - class: miv_simulator.network_objectives.FiringRateBoundConstraint
      name: PYR positive rate
      pop_name: PYR
      kwargs:
        min_rate: 0.0
    - class: miv_simulator.network_objectives.FiringRateBoundConstraint
      name: PVBC positive rate
      pop_name: PVBC
      kwargs:
        min_rate: 0.0
    - class: miv_simulator.network_objectives.FiringRateBoundConstraint
      name: OLM positive rate
      pop_name: OLM
      kwargs:
        min_rate: 0.0
kwargs:
  config: Network_Clamp_Microcircuit_Small_Bilash_PR.yaml
  tstop: 1250.
  checkpoint_interval: 0.
  v_init: -77.
  dt: 0.025
  cleanup: False
  verbose: False
  cache_queries: True
  output_results: False
  use_coreneuron: False
